import { useState, useEffect, useRef } from 'react';
import maplibregl from 'maplibre-gl';
import 'maplibre-gl/dist/maplibre-gl.css';

// ---------------------------------------------------------------------------
// Allergen layer definitions
// ---------------------------------------------------------------------------
interface Layer {
  id: string;
  label: string;
  description: string;
  defaultWeight: number;
  min: number;
  max: number;
  group: 'pollen' | 'pollution';
  color: string;
}

const LAYERS: Layer[] = [
  { id: 'birch',     label: 'Birch',      description: 'Bet v 1 + food cross-reactants', defaultWeight: 25.3, min: 0, max: 50, group: 'pollen',    color: '#4ade80' },
  { id: 'alder',     label: 'Alder',      description: 'Aln g 1',                        defaultWeight:  1.1, min: 0, max: 10, group: 'pollen',    color: '#22d3ee' },
  { id: 'hazel',     label: 'Hazel',      description: 'Cor a 1.0101',                   defaultWeight:  2.3, min: 0, max: 10, group: 'pollen',    color: '#a78bfa' },
  { id: 'grassland', label: 'Grassland',  description: 'Timothy Phl p 1 + p 5',          defaultWeight:  5.0, min: 0, max: 20, group: 'pollen',    color: '#86efac' },
  { id: 'plane',     label: 'Plane tree', description: 'Pla a 1',                        defaultWeight:  5.5, min: 0, max: 20, group: 'pollen',    color: '#fbbf24' },
  { id: 'no2',       label: 'NO₂',        description: 'Annual mean (DEFRA PCM)',         defaultWeight:  1.0, min: 0, max:  5, group: 'pollution', color: '#f87171' },
  { id: 'pm25',      label: 'PM2.5',      description: 'Annual mean (DEFRA PCM)',         defaultWeight:  1.0, min: 0, max:  5, group: 'pollution', color: '#fb923c' },
];

// ---------------------------------------------------------------------------
// Weight slider component
// ---------------------------------------------------------------------------
function WeightSlider({ layer, value, onChange }: {
  layer: Layer;
  value: number;
  onChange: (id: string, value: number) => void;
}) {
  return (
    <div className="flex items-center gap-3 py-2">
      <div className="w-3 h-3 rounded-full flex-shrink-0" style={{ backgroundColor: layer.color }} />
      <div className="flex-1 min-w-0">
        <div className="flex justify-between items-baseline mb-1">
          <span className="text-sm font-medium text-stone-700">{layer.label}</span>
          <span className="text-xs text-stone-400">{value.toFixed(1)}</span>
        </div>
        <input
          type="range"
          min={layer.min}
          max={layer.max}
          step={0.1}
          value={value}
          onChange={e => onChange(layer.id, parseFloat(e.target.value))}
          className="w-full h-1.5 rounded accent-stone-600 cursor-pointer"
        />
        <p className="text-xs text-stone-400 mt-0.5">{layer.description}</p>
      </div>
    </div>
  );
}

// ---------------------------------------------------------------------------
// Main component
// ---------------------------------------------------------------------------
export default function AllergenMap() {
  const mapRef = useRef<maplibregl.Map | null>(null);
  const containerRef = useRef<HTMLDivElement>(null);

  const [weights, setWeights] = useState<Record<string, number>>(
    Object.fromEntries(LAYERS.map(l => [l.id, l.defaultWeight]))
  );
  const [tilesReady, setTilesReady] = useState(false);

  // Initialise map once
  useEffect(() => {
    if (!containerRef.current || mapRef.current) return;

    mapRef.current = new maplibregl.Map({
      container: containerRef.current,
      style: 'https://basemaps.cartocdn.com/gl/positron-gl-style/style.json',
      center: [-2.5, 54.5],
      zoom: 5,
    });

    mapRef.current.addControl(new maplibregl.NavigationControl(), 'top-right');

    mapRef.current.on('load', () => {
      // Add each pre-tiled layer as a raster source
      // Tiles are generated by the R notebook and served from /tiles/<id>/{z}/{x}/{y}.png
      LAYERS.forEach(layer => {
        mapRef.current!.addSource(`src-${layer.id}`, {
          type: 'raster',
          tiles: [`/tiles/${layer.id}/{z}/{x}/{y}.png`],
          tileSize: 256,
          attribution: 'NFI / UKCEH / DEFRA',
        });
        mapRef.current!.addLayer({
          id: `lyr-${layer.id}`,
          type: 'raster',
          source: `src-${layer.id}`,
          paint: { 'raster-opacity': 0 },  // start invisible; composite shown below
        });
      });
      setTilesReady(true);
    });

    return () => { mapRef.current?.remove(); mapRef.current = null; };
  }, []);

  // Recompute composite opacity whenever weights change
  // (placeholder — full implementation requires a WebGL custom layer or COG pixel math)
  const totalWeight = Object.values(weights).reduce((a, b) => a + b, 0);

  function handleWeight(id: string, value: number) {
    setWeights(prev => ({ ...prev, [id]: value }));
  }

  function handleReset() {
    setWeights(Object.fromEntries(LAYERS.map(l => [l.id, l.defaultWeight])));
  }

  const pollenLayers    = LAYERS.filter(l => l.group === 'pollen');
  const pollutionLayers = LAYERS.filter(l => l.group === 'pollution');

  return (
    <div className="flex flex-col lg:flex-row gap-0 border border-stone-200 rounded-lg overflow-hidden">

      {/* Map */}
      <div ref={containerRef} className="w-full lg:flex-1 h-[500px] lg:h-[600px]" />

      {/* Control panel */}
      <div className="w-full lg:w-72 bg-white border-t lg:border-t-0 lg:border-l border-stone-200 p-5 overflow-y-auto lg:max-h-[600px]">
        <div className="flex justify-between items-center mb-4">
          <h2 className="font-semibold text-stone-800 text-sm">Allergen weights</h2>
          <button
            onClick={handleReset}
            className="text-xs text-stone-400 hover:text-stone-600 transition-colors"
          >
            Reset
          </button>
        </div>

        <p className="text-xs text-stone-400 mb-4 leading-relaxed">
          Drag the sliders to reflect your sensitivities. Higher weight = greater contribution to the composite index.
        </p>

        <p className="text-xs font-medium text-stone-500 uppercase tracking-wide mb-2">Pollen</p>
        <div className="divide-y divide-stone-100 mb-5">
          {pollenLayers.map(layer => (
            <WeightSlider key={layer.id} layer={layer} value={weights[layer.id]} onChange={handleWeight} />
          ))}
        </div>

        <p className="text-xs font-medium text-stone-500 uppercase tracking-wide mb-2">Air pollution</p>
        <div className="divide-y divide-stone-100">
          {pollutionLayers.map(layer => (
            <WeightSlider key={layer.id} layer={layer} value={weights[layer.id]} onChange={handleWeight} />
          ))}
        </div>

        {/* Weight summary */}
        <div className="mt-5 pt-4 border-t border-stone-100">
          <p className="text-xs text-stone-400 mb-2">Weight breakdown</p>
          <div className="space-y-1">
            {LAYERS.map(layer => (
              <div key={layer.id} className="flex items-center gap-2">
                <div className="h-1.5 rounded-full" style={{
                  backgroundColor: layer.color,
                  width: `${totalWeight > 0 ? (weights[layer.id] / totalWeight) * 100 : 0}%`,
                  minWidth: weights[layer.id] > 0 ? '2px' : '0',
                  maxWidth: '100%',
                  transition: 'width 0.2s ease',
                }} />
                <span className="text-xs text-stone-400 whitespace-nowrap">
                  {layer.label} {totalWeight > 0 ? Math.round(weights[layer.id] / totalWeight * 100) : 0}%
                </span>
              </div>
            ))}
          </div>
        </div>

        {!tilesReady && (
          <p className="text-xs text-stone-400 mt-4 italic">
            Map tiles loading… Run the R notebook export step first to generate <code>/public/tiles/</code>.
          </p>
        )}
      </div>
    </div>
  );
}
